addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.7.0")
addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent"       % "0.1.5")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.3.4")
addSbtPlugin("com.github.gseitz" % "sbt-release"         % "1.0.13")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.10")
