#!/usr/bin/groovy

pipeline {
  agent {
    kubernetes {
      defaultContainer 'scala-sbt'
      yaml '''
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-codeartifact
  containers:
  - name: scala-sbt
    image: hseeberger/scala-sbt:11.0.10_1.4.7_2.13.4
    command:
      - cat
    tty: true
  - name: aws
    image: amazon/aws-cli:2.2.18
    command:
    - cat
    tty: true
'''
    }
  }

  stages {
    stage('init') {
      steps {
        withFolderProperties {
          writeFile file: 'settings.xml', text: env.MAVEN_SETTINGS
          container('aws') {
            withAWS(role: env.AWS_CODEARTIFACT_ASSUME_ROLE, useNode: true) {
              script {
                env.CODEARTIFACT_AUTH_TOKEN = sh(script:"aws codeartifact get-authorization-token --domain emnify --domain-owner ${env.AWS_CODEARTIFACT_OWNER} --query authorizationToken --output text", returnStdout: true)
              }
            }
          }
        }
      }
    }
    stage('Build and test') {
      steps {
        sh 'sbt clean test'
      }
    }
    stage('Deploy') {
      when { branch 'master' }
      steps {
        script {
          env.GITHUB_SHA = sh(script:"git rev-parse HEAD", returnStdout: true).trim()
        }
        sh 'sbt publish'
      }
    }
  }
}